### ISSUE TITLE
建议添加掉线重新连接功能

### ISSUE THREAD

**Issue by nekocatso** [genshin-matrix/genshin-woodmen#10]
如题，本人网络环境为校园网，网络波动大且不稳定，在长时间运行的时候会经常出现掉线情况，能否在多次登录失败后自动输入密码进行登录？

**Comment by emako** [comment]
理论上可以自动重启游戏，这样也不需要输入密码（电脑有记录）。

**Comment by AMU-ZE** [comment]
哥，六个文件我都下载了但是不会安装怎么办啊，一运行GenshinWoodmen_MsixSetup_v1.7.3.exe就跟我说没有证书，我看了压缩包证书一安装跟我说过期了

**Comment by nekocatso** [comment]
> 哥，六个文件我都下载了但是不会安装怎么办啊，一运行GenshinWoodmen_MsixSetup_v1.7.3.exe就跟我说没有证书，我看了压缩包证书一安装跟我说过期了

已经去开发别的项目了，bettergenshin去了

**Comment by AMU-ZE** [comment]
> > 哥，六个文件我都下载了但是不会安装怎么办啊，一运行GenshinWoodmen_MsixSetup_v1.7.3.exe就跟我说没有证书，我看了压缩包证书一安装跟我说过期了
> 
> 已经去开发别的项目了，bettergenshin去了

哦哦我主要是想问咋安装，一点不会

**Comment by nekocatso** [comment]
> > > 哥，六个文件我都下载了但是不会安装怎么办啊，一运行GenshinWoodmen_MsixSetup_v1.7.3.exe就跟我说没有证书，我看了压缩包证书一安装跟我说过期了
> > 
> > 已经去开发别的项目了，bettergenshin去了
> 
> 哦哦我主要是想问咋安装，一点不会

那个exe安装不就行了

**Comment by AMU-ZE** [comment]
> > > > 哥，六个文件我都下载了但是不会安装怎么办啊，一运行GenshinWoodmen_MsixSetup_v1.7.3.exe就跟我说没有证书，我看了压缩包证书一安装跟我说过期了
> > > 
> > > 
> > > 已经去开发别的项目了，bettergenshin去了
> > 
> > 
> > 哦哦我主要是想问咋安装，一点不会
> 
> 那个exe安装不就行了

一安装就出现那个
![Uploading 1704039261665.jpg…]()

**Comment by AMU-ZE** [comment]
> > > > 哥，六个文件我都下载了但是不会安装怎么办啊，一运行GenshinWoodmen_MsixSetup_v1.7.3.exe就跟我说没有证书，我看了压缩包证书一安装跟我说过期了
> > > 
> > > 
> > > 已经去开发别的项目了，bettergenshin去了
> > 
> > 
> > 哦哦我主要是想问咋安装，一点不会
> 
> 那个exe安装不就行了
无法验证此应用包的发布者证书。请与系统管理员或应用开发人员联系，以获取具有验证证书的新应用包。必须验证应用包中签名的根证书和所有直接证书(Ox800B010A)
  就是这个

**Comment by emako** [comment]
证书过期了没更新，用绿色包吧
