### ISSUE TITLE
对b服检测的是哪一项注册表？

### ISSUE THREAD

**Issue by zzzqh** [genshin-matrix/genshin-woodmen#12]
重装过系统，砍树小工具识别不出B服，启动自动伐木后就卡在登录界面了，应该是在点击官服的登录按钮。

**Comment by emako** [comment]
计算机\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\原神

参考cn_gs_2.28.1.0.reg文件：
```ini
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\原神]
"UUID"="8ae919d528ab45e39487f7b106b9ab451639403361704"
"DisplayIcon"="D:\\Program Files\\Genshin Impact\\launcher.exe"
"DisplayName"="原神"
"DisplayVersion"="2.28.1.0"
"Publisher"="miHoYo Co.,Ltd"
"UninstallString"="D:\\Program Files\\Genshin Impact\\uninstall.exe"
"InstallPath"="D:\\Program Files\\Genshin Impact"
"ExeName"="launcher.exe"
"URLInfoAbout"="https://ys.mihoyo.com/main/"
"EstimatedSize"=dword:00049535
"NetworkType"="QT"


```

[cn_gs_2.28.1.0.zip](https://github.com/genshin-matrix/genshin-woodmen/files/12500009/cn_gs_2.28.1.0.zip)

**Comment by zzzqh** [comment]
导入后还是卡在登录页面，光标在密码栏点击就无后续操作了，看来不是注册表的问题

**Comment by emako** [comment]
b服检测的不是注册表，注册表B服和国服一样的，至少4.0之前是这样。
咱没装b服，你看看b服原神安装目录下的config.ini文件长什么样，目前检测这个ini文件是否有行`cps=*bilibili`判断为b服。

**Comment by emako** [comment]
https://github.com/genshin-matrix/genshin-woodmen/blob/main/src/GenshinWoodmen/Core/Compatible/CompatibleBilibili.cs#L14

**Comment by zzzqh** [comment]
是的，存在这一行

[launcher]
cps=bilibili
channel=14
sub_channel=0
game_install_path=F:/Genshin Impact/Genshin Impact Game
game_dynamic_bg_name=7f92b296633974293b1cc9ced73952f9_7419536879091846243.png
game_dynamic_bg_md5=8b375f844058d43255c33e2e4e71483a
game_version=1.4.0
is_first_exit=false
exit_type=2
game_start_name=YuanShen.exe
zh-cn_proto_version=1.0
download_flag=2
download_transaction_no=169346291372642621
task_start_posted=true
task_finish_posted=true
switch_416=false
pkg_size_info=resource

**Comment by emako** [comment]
你的`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\原神`注册表里写的原神也是安装在`F:/Genshin Impact/Genshin Impact Game`的吗？

**Comment by zzzqh** [comment]
不是，修改了一下注册表，与现在的目录匹配。现在发现鼠标会移动到登录按钮上面一点的位置，还是点不准。。

**Comment by emako** [comment]
以前可以现在不行啦？

**Comment by zzzqh** [comment]
是的，重装系统前也用过，当时没问题。不过以前是win7，现在是win11

**Comment by emako** [comment]
游戏分辨率跟系统DPI是多少？

**Comment by zzzqh** [comment]
1920*1080 DPI 125%

**Comment by emako** [comment]
> 1920*1080 DPI 125%

要不调成1440x900 DPI 100%先试试看，以前应该测过这个配对

**Comment by zzzqh** [comment]
试了一下，还是在点按钮靠上一点的位置

**Comment by emako** [comment]
装个B服我看看把

**Comment by zzzqh** [comment]
谢谢大佬，有进展了吗？还是我电脑上的特例？

**Comment by emako** [comment]
https://github.com/genshin-matrix/genshin-woodmen/releases/tag/v1.7.3
调整了垂直位置v1.7.3

**Comment by zzzqh** [comment]
感谢，确认b服没问题了
