### ISSUE TITLE
软件环境需求 help

### ISSUE THREAD

**Issue by shutdown3971** [genshin-matrix/genshin-woodmen#13]
Hi 作者

           我仔细看了环境需求，从网址：https://dotnet.microsoft.com/zh-cn/download/dotnet/6.0 下载了.NET 桌面运行时 6.0.22和.NET 运行时 6.0.22，这两个.net6.0环境。但是安装后并重启了电脑，发现还是无法让软件运行，所以只能写了一个求救case了。求帮助，图为安装后环境的截图，如果是我软件下载错误，也请麻烦指出。感谢
![image](https://github.com/genshin-matrix/genshin-woodmen/assets/60974018/8b141f8f-6201-4a8e-95ec-15b92aca3680)

**Comment by emako** [comment]
你下载的是源码，编译后的在 https://github.com/genshin-matrix/genshin-woodmen/releases 获取

**Comment by shutdown3971** [comment]
> 你下载源码的是，编译后的在https://github.com/genshin-matrix/genshin-woodmen/releases获取

哈哈哈哈 知道啦，感谢！！
