### ISSUE TITLE
两个问题，一个建议

### ISSUE THREAD

**Issue by batvbs** [genshin-matrix/genshin-woodmen#15]
1.报错的时候能否限制一下通知次数，一秒弹20个通知，永不停歇
报错原因：未点击登录按钮，无登录弹窗（这个不重要，退出账号会自动弹的） 
![image](https://github.com/GenshinMatrix/genshin-woodmen/assets/60730393/67e409ed-e1e5-4c90-af1f-6052fa91a7d2)

2.B服反复登录，偶尔登陆后登录弹窗不会消失（约5-30分钟触发一次），变成一个白色的特殊弹窗，该窗口具有以下特点
- 始终置顶显示，优先级极高
- 移动原神，白色窗口维持在原位（不跟随游戏窗口移动）
- 点击无反应，可遮挡点击
- 用第三方软件的弹窗拦截功能，可以选择并关闭白窗，定位为yuanshen.exe
- **Esc，点击 确定 退出登录**，登录窗口会刷新（恢复正常）

这个bug与本项目无关，且不影响游戏操作和脚本操作，**开门 点Z Esc都正常**，但分辨率较低时，窗口刚好**遮挡了退出按钮一部分**，导致循环卡在截图页面无法继续，需手动点击确定
解决方案：点击确认时，**鼠标往右边移动一些**，就不会被遮挡了
或者，全屏1920*1080，因登录窗口为固定分辨率大小，而退出窗口放大，不会被遮挡
![image](https://github.com/GenshinMatrix/genshin-woodmen/assets/60730393/1716e424-183a-46b0-bd02-94ca01655457)

3.建议将快捷键 F11 写到停止按钮里，把按钮拉宽。
要不然想中断会发现鼠标动不了，也不知道快捷键
![image](https://github.com/GenshinMatrix/genshin-woodmen/assets/60730393/f1ecdfa3-d1d1-448b-9808-3dfa8490589f)

**Comment by emako** [comment]
1. 目前B服也迁移到新仓库了：https://github.com/babalae/better-genshin-impact/issues/78
2. 白窗问题确实第一次听说，后面会留意对策。
3. 主要说明里写过了，UI不太想动

**Comment by emako** [comment]
https://github.com/GenshinMatrix/genshin-woodmen/issues/17
