### ISSUE TITLE
关于国际服伐木问题

### ISSUE THREAD

**Issue by HiyoriZeta** [genshin-matrix/genshin-woodmen#16]
国际服自动伐木 程序计数两到三次 游戏内实际伐木一次 
// 可能因为是国际服登入比国服需要多一项选择服务器导致的

**Comment by emako** [comment]
是的，国际服要多点一次，只是后来才知道的。。。
目前伐木功能逐步迁移到[BGI](https://github.com/babalae/better-genshin-impact)
与 https://github.com/babalae/better-genshin-impact/issues/125 问题重复。

**Comment by emako** [comment]
0.18.0以后已支持
https://github.com/babalae/better-genshin-impact/releases/

**Comment by emako** [comment]
#17
