### ISSUE TITLE
为什么我的程序界面和作者说明里的差别有点大,也没有启动键

### ISSUE THREAD

**Issue by pangpangdeduola** [genshin-matrix/genshin-woodmen#2]
![image2 zh](https://user-images.githubusercontent.com/50541172/198535294-fe0d854d-d916-414b-b183-7c550c6ec45f.png)

安装好后启动只有程序栏上有图标,右键后如下图
![jietu](https://user-images.githubusercontent.com/50541172/198534791-9ea358c0-f824-4549-aa16-17f94b8eec97.png)
点击伐木指南的话是一片空白,进游戏按F11启动也没反应
开始以为是运行环境的问题,结果更新net6.0还是老样子

**Comment by emako** [comment]
双击托盘图标显示主界面

**Comment by pangpangdeduola** [comment]
> 双击托盘图标显示主界面

双击打开是空白界面
![29180201](https://user-images.githubusercontent.com/50541172/198825553-fc5906fe-e27b-4bb7-a2a1-7d08a45b8906.png)

**Comment by emako** [comment]
系统版本>windows10.0.18362.0么？

**Comment by emako** [comment]
实测版本过低复现空白界面问题：
![image](https://user-images.githubusercontent.com/24737061/198845315-eae0f4e0-ce75-412d-ba61-fb7f8050a86b.png)

**Comment by emako** [comment]
#### 计划v1.6.4增加版本提示，示例：
![image](https://user-images.githubusercontent.com/24737061/198846659-f9e539d8-4bd8-44e3-8e1b-c71f1e933172.png)
---
如果你在v1.6.4收到这个提示说明版本不支持。

**Comment by pangpangdeduola** [comment]
1.6.4未提示版本问题,是不是系统过高也会有bug
![21030131210](https://user-images.githubusercontent.com/50541172/198863654-84c2f848-66bf-4609-b17e-8dc5ced5ca7d.png)

**Comment by pangpangdeduola** [comment]
> #### 计划v1.6.4增加版本提示，示例：
> ## ![image](https://user-images.githubusercontent.com/24737061/198846659-f9e539d8-4bd8-44e3-8e1b-c71f1e933172.png)
> 如果你在v1.6.4收到这个提示说明版本不支持。

v1.6.4未提示,可能版本过高也会出现不兼容?
![21030131210](https://user-images.githubusercontent.com/50541172/198871870-c458a350-b36c-450a-a362-1eac238c2cab.png)

**Comment by emako** [comment]
#### 经过排查可能是某些设备不支持WMI接口（比如非笔记本主屏幕）导致窗体构造报错。
#### 后面会在不支持的设备尝试跳过接口，表现为调节亮度功能无效果（而且这本来是给笔记本设计的功能）。
---
尝试获取[v1.6.5](https://github.com/genshin-matrix/genshin-woodmen/releases/tag/v1.6.5)看看能不能修复

**Comment by pangpangdeduola** [comment]
> 

1.6.5已经确定能正常使用了,还有个小bug是点击伐木指南无反应,但不影响使用

**Comment by pangpangdeduola** [comment]
> #### 经过排查可能是某些设备不支持WMI接口（比如非笔记本主屏幕）导致窗体构造报错。
> #### 后面会在不支持的设备尝试跳过接口，表现为调节亮度功能无效果（而且这本来是给笔记本设计的功能）。
> 尝试获取[v1.6.5](https://github.com/genshin-matrix/genshin-woodmen/releases/tag/v1.6.5)看看能不能修复

1.6.5已经确定能正常使用了,还有个小bug是点击伐木指南无反应,但不影响使用
