### ISSUE TITLE
不支持21:9分辨率，经过测试应该是游戏自身问题。

### ISSUE THREAD

**Issue by YouKnowMyEggs** [genshin-matrix/genshin-woodmen#3]
21:9分辨率下，游戏的退出按钮位置相比1920\*1080其实在左下角偏右边些。解决办法为：先在游戏内把2560\*1080设置成1920\*1080分辨率，大退游戏后重新进入游戏，画面再设置为2560\*1080，此时两边被拉伸，退出按钮和1920\*1080在同一位置，程序可以正常使用。希望作者可以直接支持2560\*1080的分辨率。感谢！

**Comment by emako** [comment]
姑且计划v1.6.7加入支持，你这什么屏幕还有这种选项。

**Comment by YouKnowMyEggs** [comment]
> 姑且计划v1.6.7加入支持，你这什么屏幕还有这种选项。

LG 21:9的带鱼屏，不是标准的2K。

**Comment by emako** [comment]
现在可以尝试获取[v1.6.7](https://github.com/genshin-matrix/genshin-woodmen/releases/tag/v1.6.7)修复问题。

**Comment by YouKnowMyEggs** [comment]
已解决。
