### ISSUE TITLE
建议增加路线功能

### ISSUE THREAD

**Issue by jiongjiongJOJO** [genshin-matrix/genshin-woodmen#4]
频繁的登出登录，原神服务器会拒绝客户端（单设备）登录，需要过一段时间才会恢复，虽然不会封号，但多少都是有些风险的。

所以建议增加一些简单的路线，通过口袋锚点回到原点的方式循环，避免来回重新登陆。

**Comment by emako** [comment]
大家的木头都9999了，没见过拒绝登录。难道是米家新功能。

不重登要砍满11颗树循环，没有简单的做法。
