### ISSUE TITLE
怎么调整延时参数哇

### ISSUE THREAD

**Issue by leafmoes** [genshin-matrix/genshin-woodmen#5]

**Comment by emako** [comment]
![image](https://user-images.githubusercontent.com/24737061/204102288-4207f9ce-e439-466f-82e2-0f0846799b93.png)
![image](https://user-images.githubusercontent.com/24737061/204102334-a097eca1-0f7b-43b8-a090-b54aba02fc65.png)
单位：毫秒

**Comment by leafmoes** [comment]
显示这样
![image](https://user-images.githubusercontent.com/44945631/204114998-fba18944-8d6f-42bd-95ca-1fda577418bc.png)

**Comment by emako** [comment]
> C:\Users\改成你的用户名\AppData\Roaming\genshin-woodmen\genshin-woodmen.yaml
类似上面的路径存在么？

**Comment by JoshYEn** [comment]
C:\Users\XXX\AppData\Local\Packages\c17bc862-e10e-4618-b717-e47dd2bf65c8_yezrnz08q8jyw\LocalCache\Roaming\genshin-woodmen

供参考，Win11下是这个路径

**Comment by emako** [comment]
> C:\Users\XXX\AppData\Local\Packages\c17bc862-e10e-4618-b717-e47dd2bf65c8_yezrnz08q8jyw\LocalCache\Roaming\genshin-woodmen
> 
> 供参考，Win11下是这个路径

修改这个目录下的.yaml配置有生效么？

**Comment by emako** [comment]
~~记录一下可能的问题：~~
~~> from https://learn.microsoft.com/zh-cn/dotnet/maui/platform-integration/storage/file-system-helpers?tabs=windows&view=net-maui-7.0~~

~~FileSystem.AppDataDirectory~~
~~返回 LocalFolder 备份到云的目录。~~

可能是系统核心版本≤1809，对`C:\Users\{user_name}\AppData\Roaming\`目录写操作会被重定向到`C:\Users\{user_name}\AppData\Local\Packages\{pack_name}\LocalCache\Roaming`，但读操作没有重定向或第三方软件（比如记事本）无法自动重定向导致。

见下面链接

**Comment by emako** [comment]
> https://learn.microsoft.com/zh-cn/windows/msix/desktop/desktop-to-uwp-behind-the-scenes
> https://learn.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-behind-the-scenes

![image](https://user-images.githubusercontent.com/24737061/205991869-125407de-417f-4579-999c-78791258dece.png)

**Comment by emako** [comment]
@JoshYEn @leafmoes  得提供一下win核心版本号。

---
使用便携版（非MSIX和非EXE安装包），或许可以避免问题。

**Comment by JoshYEn** [comment]
系统版本22H2
修改这个目录下的yaml文件有效，硬盘中只有这个文件夹下存在genshin-woodmen的yaml配置。

不影响使用，但无法从软件跳转到这个配置文件。

**Comment by emako** [comment]
![image](https://user-images.githubusercontent.com/24737061/206082907-ba95e105-d052-4be3-a1e7-3ba7da54ab3e.png)
@JoshYEn

**Comment by leafmoes** [comment]
该问题已被解决😊
