### ISSUE TITLE
指南里的松木单点位地点更换建议

### ISSUE THREAD

**Issue by leafmoes** [genshin-matrix/genshin-woodmen#6]
指南里是雪山点位，一次只能18，蒙德城大教堂下方一次24个
![原神 2022_11_27 9_13_03](https://user-images.githubusercontent.com/44945631/204114912-292b5475-3b91-4550-8c7f-ba89ef7e0b9f.png)

**Comment by emako** [comment]
啊，这个忘记更新了，后续会补上

**Comment by emako** [comment]
> https://github.com/genshin-matrix/genshin-woodmen/releases/tag/v1.6.8
