### ISSUE TITLE
希望增加对B服的适配

### ISSUE THREAD

**Issue by March7online** [genshin-matrix/genshin-woodmen#7]
B服退出重进需要点击一下登录
![屏幕截图(370)](https://user-images.githubusercontent.com/93416761/205431060-35a43803-34ac-4955-ada2-e6c3da23dbed.png)

**Comment by emako** [comment]
虽然很建议你放弃B服。我姑且安装一个试试看吧

**Comment by March7online** [comment]
> 虽然很建议你放弃B服。我姑且安装一个试试看吧

ヾ(≧∇≦谢谢≧∇≦)ノ

**Comment by emako** [comment]
肝出来了。。。

![image](https://user-images.githubusercontent.com/24737061/205450988-572e3b41-fd26-4bd0-9996-9b29cb7b20f7.png)

> v1.7.0上线功能

**Comment by March7online** [comment]
> 肝出来了。。。
> 
> ![image](https://user-images.githubusercontent.com/24737061/205450988-572e3b41-fd26-4bd0-9996-9b29cb7b20f7.png)
> 
> > v1.7.0上线功能

![18f4138745af166.jpg](https://user-images.githubusercontent.com/93416761/205451095-dc36a35c-14dc-416c-90cc-f2c46bb9e44a.jpg)

**Comment by emako** [comment]
可以展开你的尝试[v1.7](https://github.com/genshin-matrix/genshin-woodmen/releases/tag/v1.7)

**Comment by March7online** [comment]
> 可以展开你的尝试[v1.7](https://github.com/genshin-matrix/genshin-woodmen/releases/tag/v1.7)
![屏幕截图(372)](https://user-images.githubusercontent.com/93416761/205453001-deed6a26-7db2-4908-b6f3-47eb959300d1.png)
登陆时点击的位置好像不太对,点到了密码的位置

**Comment by emako** [comment]
你是多少DPI？

**Comment by March7online** [comment]
> 你是多少DPI？

![屏幕截图_20221204_011346](https://user-images.githubusercontent.com/93416761/205453215-617cf2d2-6bc0-4193-b40c-583b78ed7ff8.png)

**Comment by emako** [comment]
![image](https://user-images.githubusercontent.com/24737061/205453252-a10681c1-702e-4661-8c97-c97a66af4e22.png)

**Comment by March7online** [comment]
> ![image](https://user-images.githubusercontent.com/24737061/205453252-a10681c1-702e-4661-8c97-c97a66af4e22.png)
> 

我是125%我改100试试

**Comment by emako** [comment]
看看你的显示器分辨率多少，是1920x1080么？不是说游戏

**Comment by March7online** [comment]
> 看看你的显示器分辨率多少，是1920x1080么？不是说游戏

![image](https://user-images.githubusercontent.com/93416761/205453445-47c75b4e-3fd2-4c9c-b3a5-fc7bd13c7525.png)
wo我把缩放改成100了,但是点击的位置还是不对,还是会点到密码上

**Comment by March7online** [comment]
我看了下额外说明,可能是因为我的系统是重装的,注册表里面没有原神的安装记录,我重装一下原神试试

**Comment by emako** [comment]
你可以尝试下不启动游戏，打开伐木姬点启动。
如果提示Genshin Impact not installed.就是这个原因了。

**Comment by March7online** [comment]
> 你可以尝试下不启动游戏，打开伐木姬点启动。 如果提示Genshin Impact not installed.就是这个原因了。

手快了,已经在重装了QAQ

**Comment by March7online** [comment]
可以正常使用![25d9cccaa454a3d8.gif](https://user-images.githubusercontent.com/93416761/205469386-5b81fafb-b5c6-4b82-8eea-d72592c96ae7.gif)

**Comment by emako** [comment]
(u u✿)
