### ISSUE TITLE
AppData 配置文件问题

### ISSUE THREAD

**Issue by JoshYEn** [genshin-matrix/genshin-woodmen#8]
系统版本是22H2，22621.900
<img width="475" alt="截屏2022-12-07 23 20 27" src="https://user-images.githubusercontent.com/11255434/206218548-e91bb68f-552c-423d-95a1-3d129acbb7af.png">

**Comment by emako** [comment]
#5

**Comment by emako** [comment]
> https://learn.microsoft.com/zh-cn/windows/msix/desktop/desktop-to-uwp-behind-the-scenes
> https://learn.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-behind-the-scenes

仔细阅读了一下文档，首次使用MSIX包版本会有这种问题。
首次使用的是便携包的话，已在C:\Users\user_name\AppData创建过的文件才不会被重定向。

**Comment by emako** [comment]
~~后面参考一下WinUI3的默认模板改改保存路径好了。~~

**Comment by emako** [comment]
[v1.7.1](https://github.com/genshin-matrix/genshin-woodmen/releases/tag/v1.7.1)迁移了配置文件路径
